apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod


# An example of injecting a config map (whole)
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#       envFrom:
#         - configMapRef:
#             name: app-config


# An example of injecting a single value from a config map
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#       env:
#       - name: app-color
#         valueFrom:
#           configMapKeyRef:
#             name: app-config
#             key: app-color