apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-1
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  # Next two lines can be replaced with something else, based on the storage solution
  hostPath:
    path: /tmp/data
  # For instance
  # awsElasticBlockStore:
  #   volumeID: <volume-id>
  #   fsType: ext4