apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: my-scheduler

# Then we define the class that pod will use
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#   schedulerName: my-scheduler