apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: faws # Encoded format
  DB_User: fwaf
  DB_Password: fwasf

# An example of injecting a secret (whole secret)
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#       envFrom:
#         - secretRef:
#             name: app-secret

# An example of injecting a secret (single)
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#       env:
#         - name: DB_PASSWORD
#           valueFrom:
#             - secretKeyRef:
#               name: app-config
#               key: DB_Password