apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: default

# Assosiating contaienr witha a service account
# apiVersion: v1
# kind: Pod
# metadata:
#   name: Demo-Pod
#   labels:
#     app: nginx
#     tier: something
# spec:
#   containers:
#     - name: First-Container
#       image: nginx
#   servcieAccountName: dashboard-sa